name: 'Terraform destroy'
 
on:
  workflow_dispatch:
 
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
 
    defaults:
      run:
        shell: bash
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
 
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.working-directory}}
 
 
    - name: Terraform destroy
      run: terraform destroy -auto-approve  
      working-directory: ${{env.working-directory}}

      
